<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-macos</TargetFramework>
    <SupportedOSPlatformVersion>11.0</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <RootNamespace>MikumikuDance.Mac</RootNamespace>
    <AssemblyName>MikumikuDance.Mac</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.0.1641" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.0.1641" />
  </ItemGroup>

  <ItemGroup>
    <MonoGameContentReference Include="Content\Content.mgcb" />
  </ItemGroup>
</Project>