<Project Sdk="MSBuild.Sdk.Extras">
	<PropertyGroup>
		<TargetFrameworks>net40;netstandard2.0</TargetFrameworks>

		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<PackageId>MikumikuDance.Framework.Core</PackageId>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<PropertyGroup>
		<NoWarn>NU5128</NoWarn>
		<DefineConstants>WINDOWS;PORTABLE</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\MikumikuDance.Framework.BulletX\MikumikuDance.Framework.BulletX.csproj" />
		<ProjectReference Include="..\MikumikuDance.Framework.Primitives\MikumikuDance.Framework.Primitives.csproj" />
		<ProjectReference Include="..\MikumikuDance.Framework.Abstractions\MikumikuDance.Framework.Abstractions.csproj" />
	</ItemGroup>

	<Import Project="../../Build/net40.props" Condition=" '$(TargetFramework)' == 'net40' " />
	<Import Project="../../Build/netstandard2.0.props" Condition=" '$(TargetFramework)' == 'netstandard2.0' " />
</Project>
