<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-android</TargetFramework>
		<SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
		<OutputType>Exe</OutputType>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationId>com.sprintor.mikumikudance</ApplicationId>
		<ApplicationVersion>1</ApplicationVersion>
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<!--
      Enables trim analyzers and full trimming during Release mode.
      To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/trimming-options#trimming-granularity
    -->
		<TrimMode Condition=" $(Configuration) == 'Release' ">full</TrimMode>
	</PropertyGroup>


	<ItemGroup Condition=" '$(TargetFramework)' == 'net8.0-android' ">
		<PackageReference Include="MonoGame.Framework.Android" Version="3.8.0.1641"></PackageReference>
		<PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.0.1641"></PackageReference>
	</ItemGroup>


	<ItemGroup>
	  <Folder Include="Content\obj\Android\Content\" />
	</ItemGroup>
</Project>