<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-ios</TargetFramework>
    <SupportedOSPlatformVersion>11.0</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <RootNamespace>MikumikuDance.iOS</RootNamespace>
    <AssemblyName>MikumikuDance.iOS</AssemblyName>
    <ApplicationId>project.MonoGame.MikumikuDance.iOS</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    <RuntimeIdentifiers>iossimulator-x64;ios-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <MtouchDebug>true</MtouchDebug>
    <MtouchLink>None</MtouchLink>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <MtouchLink>SdkOnly</MtouchLink>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.iOS" Version="3.8.0.1641" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.0.1641" />
  </ItemGroup>

  <ItemGroup>
    <BundleResource Include="Default.png" />
    <BundleResource Include="GameThumbnail.png" />
  </ItemGroup>

  <ItemGroup>
    <MonoGameContentReference Include="Content\Content.mgcb" />
  </ItemGroup>
</Project>